export const CHANGE_AMOUNTTOSEND = "CHANGE_AMOUNTTOSEND";
export const CHANGE_AMOUNTTORECEIVE = "CHANGE_AMOUNTTORECEIVE";
export const CHANGE_CURRENCYTOSEND = "CHANGE_CURRENCYTOSEND";
export const CHANGE_CURRENCYTORECEIVE = "CHANGE_CURRENCYTORECEIVE";